### ISSUE TITLE
プロジェクト全体に関する相談窓口はどこ？

### ISSUE THREAD

**Issue by hidao80** [my-first-qiita/common#1]
おそらくこの Organizations は

1. BOT のコードリポジトリ (my-first-qiita/BOT が作られる or my-first-qiita/PHP に配置される？)
2. BOT 運用および Organizations 運用に関する取り決めをまとめるリポジトリ (my-first-qiita/COMMON が相当する？)
3. BOT が投稿するコンテンツ群のリポジトリ (my-first-qiita/items が相当する？)

の 3 つのリポジトリで運用されるようになると考えていますが、リポジトリまたぎの相談や特定のリポジトリに対して起こすと不適当な issue (当 issue のようなもの) は、どのリポジトリで管理しますか？

それとも、プロジェクトマネジメント用の別システムを用意しますか？

**Comment by KEINOS** [comment]
そうですね。各リポジトリをふかんでディスカッションできる場所が必要ですね。

Qiita縛りを逆にQiitaの利点にしたいのでMastodonをSlack的な使い方にしたいとは考えているのですが、リポジトリとOrganizationの構成・関係をまずは明確にしたいと思います。

**Comment by KEINOS** [comment]
This issue was moved to my-first-qiita/items#1
